server:
  port: 1001
eureka:
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    prefer-ip-address: true
    #Eureka\u5BA2\u6237\u9700\u8981\u591A\u957F\u65F6\u95F4\u53D1\u9001\u5FC3\u8DF3\u7ED9eureka\u670D\u52A1\u5668\uFF0C\u8868\u660E\u5B83\u4ECD\u7136\u6D3B\u7740,\u9ED8\u8BA4\u4E3A30 \u79D2
    lease-renewal-interval-in-seconds: 5
    #Eureka\u670D\u52A1\u5668\u5728\u63A5\u6536\u5230\u5B9E\u4F8B\u7684\u6700\u540E\u4E00\u6B21\u53D1\u51FA\u7684\u5FC3\u8DF3\u540E\uFF0C\u9700\u8981\u7B49\u5F85\u591A\u4E45\u624D\u53EF\u4EE5\u5C06\u6B64\u5B9E\u4F8B\u5220\u9664\uFF0C\u9ED8\u8BA4\u4E3A90\u79D2
    lease-expiration-duration-in-seconds: 10
    #\u4F7F\u7528IP\u548C\u7AEF\u53E3\u4F5C\u4E3A\u5B9E\u4F8B\u540D\u79F0
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    #\u8868\u793Aeureka client\u95F4\u9694\u591A\u4E45\u53BB\u62C9\u53D6\u670D\u52A1\u6CE8\u518C\u4FE1\u606F\uFF0C\u9ED8\u8BA4\u4E3A30\u79D2\uFF0C\u5BF9\u4E8Egateway-api\uFF0C\u5982\u679C\u8981\u8FC5\u901F\u83B7\u53D6\u670D\u52A1\u6CE8\u518C\u72B6\u6001\uFF0C\u53EF\u4EE5\u7F29\u5C0F\u8BE5\u503C\uFF0C\u6BD4\u59825\u79D2
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://192.168.1.7:9001/eureka/
    fetch-registry: true

spring:
  application:
    name: javastudy
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      initial-size: 1
#      max-active: 50
#      #min-idle: 10
#      max-wait: 180000 #Default value is 30000 (30 seconds)60000->180000
#      time-between-eviction-runs-millis: 600000 #\u914D\u7F6E\u95F4\u9694\u591A\u4E45\u624D\u8FDB\u884C\u4E00\u6B21\u68C0\u6D4B\uFF0C\u68C0\u6D4B\u9700\u8981\u5173\u95ED\u7684\u7A7A\u95F2\u8FDE\u63A5\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2\uFF0Cdefault value is 5000 (5 seconds)->60000-600000
#      min-evictable-idle-time-millis: 3600000 #\u914D\u7F6E\u4E00\u4E2A\u8FDE\u63A5\u5728\u6C60\u4E2D\u6700\u5C0F\u751F\u5B58\u7684\u65F6\u95F4\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2\uFF0Cdefault value is 60000 (60 seconds)->300000-3600000
#      pool-prepared-statements: false #\u662F\u5426\u7F13\u5B58preparedStatement\uFF0C\u4E5F\u5C31\u662FPSCache\u3002PSCache\u5BF9\u652F\u6301\u6E38\u6807\u7684\u6570\u636E\u5E93\u6027\u80FD\u63D0\u5347\u5DE8\u5927\uFF0C\u6BD4\u5982\u8BF4oracle\u3002\u5728mysql\u4E0B\u5EFA\u8BAE\u5173\u95ED\u3002
      #      url: jdbc:mysql://mysql-cn-north-1-2ac7b75e82d44dce.rds.jdcloud.com:3306/business?useUnicode=true&characterEncoding=utf-8
      #      username: spark
      #      password: G83qNKdz
      #      url: jdbc:mysql://192.168.1.200:3306/business?useUnicode=true&characterEncoding=utf-8
      #      username: root
      #      password: spark@2019
#      url: jdbc:mysql://localhost:3306/business?useUnicode=true&characterEncoding=utf-8
#      username: root
#      password: root
#      driver-class-name: com.mysql.jdbc.Driver

#mybatis:
#  #\u9700\u8981\u914D\u5408\u81EA\u52A8\u626B\u63CFMappers\u5305
#  type-aliases-package: com.eeparking.service.team.dao
#  #mapper.xml\u6240\u5728\u4F4D\u7F6E
#  mapper-locations: classpath:mappers/*.xml
#  config-location: classpath:mybatis-config.xml